# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Trigger another repo test

on:
  push:
    branches: [ master ]


jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: trigger the workflow from selenium repo
      run: |
           echo "trigger and wait"
           
    - name: trigger SaymaM repo
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: 'SaymaM'
          repo: 'Dev'
          github_token: ${{ secrets.TEST_ACCESS_TOKEN }}
          workflow_file_name: 'maven.yml'
          ref: 'master'
          #workflow_file_name: 'maven.yml' 
          
    - name: QA trigger
      run: |
           echo "trigger and done"
           
  display:

    runs-on: ubuntu-latest

    steps:
    - name: print a msg
      env:
        message: assignment sesh holo
        new_msg: try print
      run: echo $message $new_msg
 
